#include "cli_help.h"

namespace draxul
{

const char* cli_help_text() noexcept
{
    return
        "Draxul terminal and agent harness\n\n"
        "Usage:\n"
        "  draxul [launch options]\n"
        "  draxul <space|agent|pane|integration> <command> [options]\n\n"
        "Launch:\n"
        "  draxul [--session <id>] [--new-session] [--host <kind>]\n"
        "  --host <kind>                 powershell, bash, zsh, wsl, nvim,\n"
        "                                markdown, kanban, nanovg-demo, or an\n"
        "                                enabled megacity, bioview, satview,\n"
        "                                or score product host\n"
        "  --source <path>               Source file or directory for a product host\n"
        "  --command <command>           Override the selected host command\n"
        "  --session-name <name>         Set the launched Session display name\n\n"
        "Server and Sessions:\n"
        "  draxul --server\n"
        "  draxul --server-status [--json]\n"
        "  draxul --list-sessions [--json]\n"
        "  draxul --rename-session --session <id> --session-name <name>\n"
        "  draxul --delete-session --session <id> [--yes]\n"
        "  draxul --delete-all-sessions --yes\n"
        "  draxul --shutdown-server [--yes]\n\n"
        "Spaces (requires a running UI):\n"
        "  draxul space list [--session <id>] [--json]\n"
        "  draxul space get <space-id> [--session <id>] [--json]\n"
        "  draxul space focus <space-id> [--session <id>]\n\n"
        "Agents:\n"
        "  draxul agent list [--session <id>] [--json]\n"
        "  draxul agent get <instance-id> [--session <id>] [--json]\n"
        "  draxul agent explain <instance-id> [--session <id>] [--json]\n"
        "  draxul agent start <profile-id> [--cwd <path>] [--space <id>]\n"
        "                     [--session <id>] [-- <agent arguments...>]\n"
        "  draxul agent focus <instance-id> [--session <id>]\n"
        "  draxul agent restart <instance-id> [--session <id>]\n"
        "  draxul agent send <instance-id> --text <text> [--session <id>]\n"
        "  draxul agent keys <instance-id> <key> [key...] [--session <id>]\n"
        "  draxul agent wait <instance-id> --until <state,state>\n"
        "                    [--timeout <duration>] [--session <id>] [--json]\n\n"
        "Panes:\n"
        "  draxul pane read <pane-id> [--lines <1..200>]\n"
        "                   [--session <id>] [--json]\n\n"
        "Agent integrations:\n"
        "  draxul integration status [codex|claude] [--json]\n"
        "  draxul integration install <codex|claude> [--json]\n"
        "  draxul integration uninstall <codex|claude> [--json]\n\n"
        "Common options:\n"
        "  --server-runtime-dir <path>   Select or isolate a server runtime\n"
        "  --server-shell <kind>         powershell, bash, zsh, or wsl\n"
        "  --server-command <path>       Override the server shell executable\n"
        "  --server-working-dir <path>  Initial server shell directory\n"
        "  --server-scrollback-lines N  Retained rows (0..1000000)\n"
        "  --log-file <path>             Write diagnostic logs to a file\n"
        "  --log-level <level>           error, warn, info, debug, or trace\n"
        "  --continuous-refresh          Allow continuously animated hosts\n"
        "  --no-vblank                   Disable synchronized presentation\n"
        "  --console                     Allocate a console on Windows\n"
        "  --json                        Emit JSON where supported\n"
        "  --yes                         Confirm a destructive server operation\n"
        "  -h, --help                    Show this help\n\n"
        "Shell launches attach to the per-user Draxul server. Neovim and\n"
        "product hosts remain client-local.\n";
}

} // namespace draxul
