#include "cli_help.h"

namespace draxul
{

const char* cli_help_text() noexcept
{
    return "Draxul terminal and agent harness\n\n"
           "Usage:\n"
           "  draxul [launch options]\n"
           "  draxul <space|tab|pane|split|layout|plugin|agent|integration> <command> [options]\n\n"
           "Launch:\n"
           "  draxul [--session <id>] [--new-session] [--host <kind>]\n"
           "  --host <kind>                 powershell, bash, zsh, wsl, nvim,\n"
           "                                markdown, kanban, or nanovg-demo\n"
           "  --plugin <id>                 Launch a product plugin pane\n"
           "                                (e.g. dev.draxul.scoreview)\n"
           "  --plugin-config <json>        Configuration JSON for --plugin\n"
           "  --source <path>               Source file or directory for the selected host\n"
           "  --command <command>           Override the selected host command\n"
           "  --session-name <name>         Set the launched Session display name\n\n"
           "Server and Sessions:\n"
           "  draxul --server\n"
           "  draxul --server-status [--json]\n"
           "  draxul --list-sessions [--json]\n"
           "  draxul --rename-session --session <id> --session-name <name>\n"
           "  draxul --delete-session --session <id> [--yes]\n"
           "  draxul --delete-all-sessions --yes\n"
           "  draxul --shutdown-server [--yes]\n\n"
           "Server topology:\n"
           "  draxul space list [--session <id>] [--json]\n"
           "  draxul space get <space-id> [--session <id>] [--json]\n"
           "  draxul space create --name <name> [--root <path>]\n"
           "  draxul space rename <space-id> --name <name>\n"
           "  draxul space close <space-id>\n"
           "  draxul tab list --space <space-id> [--json]\n"
           "  draxul tab get <tab-id> [--json]\n"
           "  draxul tab create --space <space-id> [--name <name>]\n"
           "                    [--cwd <path> | --plugin <id> [--plugin-config <json>]]\n"
           "  draxul tab rename <tab-id> --name <name>\n"
           "  draxul tab move <tab-id> --delta <-1|1>\n"
           "  draxul tab close <tab-id>\n"
           "  draxul pane list [--space <id>] [--tab <id>] [--json]\n"
           "  draxul pane get <pane-id> [--json]\n"
           "  draxul pane split <pane-id|--current>\n"
           "                    --direction <left|right|up|down> [--ratio <value>]\n"
           "                    [--cwd <path> | --plugin <id> [--plugin-config <json>]]\n"
           "  draxul pane rename <pane-id> --name <name>\n"
           "  draxul pane swap <pane-id> <pane-id>\n"
           "  draxul pane move <pane-id> --target <pane-id>\n"
           "                   --direction <left|right|up|down> [--ratio <value>]\n"
           "  draxul pane restart|close <pane-id>\n"
           "  draxul pane run <pane-id|--current> --command <command>\n"
           "  draxul pane send <pane-id|--current> --text <text>\n"
           "  draxul pane keys <pane-id|--current> <key> [key...]\n"
           "  draxul pane read <pane-id|--current> [--lines <1..200>] [--json]\n"
           "  draxul pane wait-output <pane-id|--current> --text <text>\n"
           "                          [--timeout <duration>] [--lines <1..200>] [--json]\n"
           "  draxul split list --tab <tab-id> [--json]\n"
           "  draxul split set <node-id> --ratio <0.1..0.9>\n"
           "  draxul split equalize --tab <tab-id>\n"
           "  draxul layout validate <file|-> [--json]\n"
           "  draxul layout apply <file|-> [--dry-run] [--json]\n\n"
           "Plugins (local discovery):\n"
           "  draxul plugin list [--json]\n"
           "  draxul plugin get <plugin-id> [--json]\n"
           "  draxul plugin reload <plugin-id> [--session <id>] [--json]\n\n"
           "UI-local navigation:\n"
           "  draxul space focus <space-id> [--session <id>]\n\n"
           "Agents:\n"
           "  draxul agent list [--session <id>] [--json]\n"
           "  draxul agent get <instance-id> [--session <id>] [--json]\n"
           "  draxul agent explain <instance-id> [--session <id>] [--json]\n"
           "  draxul agent start <profile-id> [--cwd <path>] [--space <id>]\n"
           "                     [--tab <id>] [--pane <id>] [--replace]\n"
           "                     [--session <id>] [-- <agent arguments...>]\n"
           "  draxul agent focus <instance-id> [--session <id>]\n"
           "  draxul agent restart <instance-id> [--session <id>]\n"
           "  draxul agent send|prompt <instance-id> --text <text> [--session <id>]\n"
           "  draxul agent keys <instance-id> <key> [key...] [--session <id>]\n"
           "  draxul agent wait <instance-id> --until <state,state>\n"
           "                    [--timeout <duration>] [--session <id>] [--json]\n\n"
           "Agent integrations:\n"
           "  draxul integration status [codex|claude] [--json]\n"
           "  draxul integration install <codex|claude> [--json]\n"
           "  draxul integration uninstall <codex|claude> [--json]\n\n"
           "Common options:\n"
           "  --server-runtime-dir <path>   Select or isolate a server runtime\n"
           "  --server-shell <kind>         powershell, bash, zsh, or wsl\n"
           "  --server-command <path>       Override the server shell executable\n"
           "  --server-working-dir <path>  Initial server shell directory\n"
           "  --server-scrollback-lines N  Retained rows (0..1000000)\n"
           "  --log-file <path>             Write diagnostic logs to a file\n"
           "  --log-level <level>           error, warn, info, debug, or trace\n"
           "  --continuous-refresh          Allow continuously animated hosts\n"
           "  --no-vblank                   Disable synchronized presentation\n"
           "  --console                     Allocate a console on Windows\n"
           "  --json                        Emit JSON where supported\n"
           "  --current                     Use the enclosing pane's injected route id\n"
           "  --yes                         Confirm a destructive server operation\n"
           "  -h, --help                    Show this help\n\n"
           "Shell launches attach to the per-user Draxul server. Neovim and\n"
           "product hosts remain client-local.\n";
}

} // namespace draxul
