add_library(draxul-file-monitor STATIC src/file_monitor.cpp)
set_target_properties(draxul-file-monitor PROPERTIES POSITION_INDEPENDENT_CODE ON)
target_include_directories(draxul-file-monitor PUBLIC include)
find_package(Threads REQUIRED)
target_link_libraries(draxul-file-monitor PRIVATE Threads::Threads)

if(APPLE)
    target_sources(draxul-file-monitor PRIVATE src/file_monitor_mac.cpp)
    find_library(DRAXUL_FILE_MONITOR_CORESERVICES CoreServices REQUIRED)
    target_link_libraries(draxul-file-monitor PRIVATE ${DRAXUL_FILE_MONITOR_CORESERVICES})
elseif(WIN32)
    target_sources(draxul-file-monitor PRIVATE src/file_monitor_win.cpp)
elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    target_sources(draxul-file-monitor PRIVATE src/file_monitor_linux.cpp)
else()
    target_sources(draxul-file-monitor PRIVATE src/file_monitor_unsupported.cpp)
endif()

draxul_configure_internal_targets_in_directory("${CMAKE_CURRENT_SOURCE_DIR}")
